/* 


README !!!!!!

All JavaScript not marked with comments is made by me.
All JavaScript marked with comments have been generated by AI **for the purpose of ARIA and screen reading**.
I spoke with you in-person and you approved of me generating the ARIA via AI.


*/

let people = [];

let listContainer = document.querySelector('main');
let sortBy;
let addFormButton = document.getElementById('addButton');
let sortByButton = document.getElementById('sortButton');
let addForm = document.getElementById('newPersonForm');
let sortForm = document.getElementById('sortByForm');
let select = sortForm.querySelector('#sortRadioContainer');

// Accessibility Helper: Toggle menu visibility and manage aria-expanded state
function toggleForm(formToShow, formToHide, buttonToExpand, buttonToCollapse) {
    const isHidden = formToShow.classList.toggle('hide');
    formToHide.classList.add('hide');
    
    buttonToExpand.setAttribute('aria-expanded', !isHidden);
    buttonToCollapse.setAttribute('aria-expanded', 'false');
}

addFormButton.addEventListener('click', () => {
    toggleForm(addForm, sortForm, addFormButton, sortByButton);
});

sortByButton.addEventListener('click', () => {
    toggleForm(sortForm, addForm, sortByButton, addFormButton);
});

function findMin(method) {
    let num = 1000;
    people.forEach(person => {
        if (person[method] < num) {
            num = person[method];
        }
    });
    return num;
}

function findMax(method) {
    let num = 0;
    people.forEach(person => {
        if (person[method] > num) {
            num = person[method];
        }
    });
    return num;
}

function template(person, method, min, max) {
    let retrieve = person[method];
    let unit = method === "age" ? "years old" : "inches tall";
    let genderLabel = person.gender === "M" ? "Male" : "Female";
    let color = person.gender === "M" ? "#C6E2FF" : "#FFB6C1";

    switch (method) {
        case 'name':
            return `
                <li style="height:100%; background-color:${color}" class="chart-bar" aria-label="${person.name}, Gender: ${genderLabel}">
                    <p><span aria-hidden="true">${retrieve}</span><span class="sr-only">${retrieve}</span></p>
                </li>`;
        case 'age': 
        case 'height_in':
            let percentage = (min === max) ? 100 : ((retrieve - min) / (max - min)) * 75 + 25;
            // Includes a clean screen-reader only sentence so users don't skip over content hidden by media queries
            return `
                <li style="height:${percentage}%; background-color:${color}" class="chart-bar" aria-label="${person.name}: ${retrieve} ${unit}, Gender: ${genderLabel}">
                    <p aria-hidden="true">${person.name}<br><span class="itemAttribute">${retrieve} ${unit}</span></p>
                    <span class="sr-only">${person.name}, ${retrieve} ${unit}</span>
                </li>`;
    }
}

function render(method) {
    if (people.length === 0) {
        listContainer.innerHTML = `<h3>Your list is empty!</h3>`;
        return;
    }
    
    // Changing container to an ordered list structure inside main for clean listing/counting in screen readers
    listContainer.innerHTML = `<ol class="chart-list" aria-label="Sorted data list"></ol>`;
    const listElement = listContainer.querySelector('.chart-list');
    
    people.forEach(person => {
        listElement.innerHTML += template(person, method, findMin(method), findMax(method));
    });
}

function compareObj(method) {
    return function(a, b) {
        if (a[method] < b[method]) return -1;
        if (a[method] > b[method]) return 1;
        return 0;
    };
}

function sortList(method) {
    switch (method) {
        case 'name':
            return people.sort(compareObj('name'));
        case 'age': 
        case 'height_in':
            return people.sort(compareObj(method));
    }
}

select.addEventListener('change', (item) => {
    sortBy = item.target.value;
    render(sortBy); 
});

sortForm.addEventListener('submit', (event) => {
    event.preventDefault(); 
    let selected = sortForm.querySelector('input[name="sortBy"]:checked');
    if (selected) {
        sortBy = selected.value;
        sortList(sortBy);
        render(sortBy);
    }
});

addForm.addEventListener('submit', (event) => {
    event.preventDefault();
    const nameInput = document.getElementById('name');
    const ageInput = document.getElementById('age');
    const heightInput = document.getElementById('height');
    const genderInput = document.querySelector('input[name="gender"]:checked');
    
    if (nameInput.value === "test" && parseInt(ageInput.value) === 0) {
        admin();
        render(sortBy);
        addForm.reset();
        return;
    }
    
    let newPerson = {
        name: nameInput.value,
        age: parseInt(ageInput.value),
        height_in: parseInt(heightInput.value),
        gender: genderInput.value
    };
    people.push(newPerson);
    render(sortBy);
    addForm.reset();
});

function admin() {
    people.push({name:"John", age:22, height_in:68, gender:"M"});
    people.push({name:"Wemby", age:22, height_in:88, gender:"M"});
    people.push({name:"Kaitlyn", age:27, height_in:62, gender:"F"});
    people.push({name:"Yedam", age:27, height_in:70, gender:"M"});
    people.push({name:"Johnathan", age:23, height_in:72, gender:"M"});
    people.push({name:"Alex", age:20, height_in:67, gender:"M"});
    people.push({name:"Jacob", age:18, height_in:66, gender:"M"});
    people.push({name:"Child", age:11, height_in:55, gender:"F"});
}

function init() {
    addForm.classList.add('hide');
    sortForm.classList.add('hide');
    addFormButton.setAttribute('aria-expanded', 'false');
    sortByButton.setAttribute('aria-expanded', 'false');
    sortBy = "height_in";
    listContainer.innerHTML = `<h3>Your list is empty!</h3>`;
}

init();